### ISSUE TITLE
Webpage Github Link broken 

### ISSUE THREAD

**Issue by vasnt** [hadley/r4ds#1135] opened 2022-11-12 15:50 UTC
github links ( https://github.com/hadley/r4ds/edit/master/index.Rmd)- located don top right on webpage (https://r4ds.had.co.nz/index.html) are broken.

**Comment by r-31415** [comment] 2022-11-13 20:42
Add to that the links to amazon books in https://r4ds.had.co.nz/exploratory-data-analysis.html#learning-more

**Comment by hadley** [comment] 2022-11-16 21:57
Duplicate of #1053

**Closed by hadley** 2022-11-16 21:57 UTC
