### ISSUE TITLE
View and edit links are broken

### ISSUE THREAD

**Issue by williamorim** [hadley/r4ds#1098] opened 2022-09-26 17:07 UTC
The view and edit links in each page are broken.
The link should refer to 

https://github.com/hadley/r4ds/blob/master/file.qmd or https://github.com/hadley/r4ds/edit/master/file.qmd 

but they're  referring to .Rmd files that no longer exist.

I was not able to fix it to make a PR. :(

<img width="172" alt="image" src="https://user-images.githubusercontent.com/8967307/192336868-0e7e0b1c-298f-4b5a-885d-734e7d0e52c4.png">

**Comment by hadley** [comment] 2022-09-26 17:28
Duplicate of #1053

**Closed by hadley** 2022-09-26 17:28 UTC
