### ISSUE TITLE
Answers to questions

### ISSUE THREAD

**Issue by PrincessK1tty** [hadley/r4ds#537] opened 2017-02-17 04:45 UTC
I'm relatively new to R. Have taken a few short intro courses but am now trying to use your book to get a more solid foundation of the basics. The exercises are great but without knowing if I've got the answers right or wrong I'm not always sure if I'm getting them.

**Comment by hadley** [comment] 2017-05-03 13:32
Duplicate of #472

**Closed by hadley** 2017-05-03 13:32 UTC
