### ISSUE TITLE
Error in compiling: "object 'lifeExp' not found" in "model-many.Rmd"

### ISSUE THREAD

**Issue by jethroppaPH** [hadley/r4ds#766] opened 2019-02-22 00:37 UTC
I am trying to compile the book using:

```
bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")
```

but it throws an error:

```
Quitting from lines 150-151 (model-many.Rmd) 
Error in eval(predvars, data, env) : object 'lifeExp' not found
Calls: local ... eval -> <Anonymous> -> model.frame.default -> eval -> eval

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile model-many.Rmd
```

I already installed the `devtools::install_github("hadley/r4ds")`, `devtools::install_github("wch/webshot")`, and `webshot::install_phantomjs()`.

***
`sessionInfo()`
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0           pillar_1.3.1         compiler_3.5.2       gapminder_0.3.0.9000 prettyunits_1.0.2   
 [6] remotes_2.0.2        tools_3.5.2          testthat_2.0.1       digest_0.6.18        pkgbuild_1.0.2      
[11] pkgload_1.0.2        gtable_0.2.0         evaluate_0.13        memoise_1.1.0        tibble_2.0.1        
[16] pkgconfig_2.0.2      rlang_0.3.1          cli_1.0.1            rstudioapi_0.9.0     curl_3.3            
[21] yaml_2.2.0           xfun_0.5             dplyr_0.8.0.1        withr_2.1.2          knitr_1.21          
[26] desc_1.2.0           fs_1.2.6             devtools_2.0.1       tidyselect_0.2.5     grid_3.5.2          
[31] rprojroot_1.3-2      webshot_0.5.1        glue_1.3.0           R6_2.4.0             processx_3.2.1      
[36] fansi_0.4.0          rmarkdown_1.11.7     bookdown_0.9.1       sessioninfo_1.1.1    purrr_0.3.0         
[41] ggplot2_3.1.0.9000   callr_3.1.1          scales_1.0.0         backports_1.1.3      ps_1.3.0            
[46] htmltools_0.3.6      usethis_1.4.0        assertthat_0.2.0     colorspace_1.4-0     labeling_0.3        
[51] utf8_1.1.4           lazyeval_0.2.1       munsell_0.5.0        crayon_1.3.4        
```

**Comment by RAJohansen** [comment] 2019-05-23 20:06
@hadley,

Has there be a fix for this? I am unable to reproduce this example as well.  Page 402 Chapter 20

by_country <- gapminder %>% 
  group_by(country,continent) %>% 
  nest()

country_model <- function(df) {
  lm(lifeExp ~ year, data = df)
}

by_country <- by_country %>%
  mutate(model = map(data, country_model))

 Error in eval(predvars, data, env) : object 'lifeExp' not found

**Comment by hadley** [comment] 2021-04-18 14:49
We're removing the modelling chapters from the 2nd ed of the book so this question is now academic.

**Closed by hadley** 2021-04-18 14:49 UTC
