### ISSUE TITLE
Problem using write_dataset

### ISSUE THREAD

**Issue by HaroldNelson** [hadley/r4ds#1389] opened 2023-03-26 23:06 UTC
This code

seattle_csv |>
  group_by(CheckoutYear) |>
  write_dataset(path = pq_path, format = "parquet")

produces the following error

Error: Invalid: In CSV column #7: Row #83240: CSV conversion error to null: invalid value '9781504752848'

**Comment by hadley** [comment] 2023-03-27 15:07
Duplicate of #1374

**Closed by hadley** 2023-03-27 15:07 UTC
