### ISSUE TITLE
Link to next section from section 18 shows as "19  Joins ' class='pagination-link' href='/joins'> 19  Joins", and is unclickable.

### ISSUE THREAD

**Issue by jpamills** [hadley/r4ds#1626] opened 2024-01-31 01:36 UTC
On the page https://r4ds.hadley.nz/missing-values.html , the right arrow link at the bottom of the page to go to the next section displays as a broken code segment, and is unclickable.

Expected behaviour: Clickable link that reads as "19 Joins". 
Current behaviour: Unclickable text that reads as: `19 
Joins
' class='pagination-link' href='/joins'>
19  Joins
`

**Comment by mine-cetinkaya-rundel** [comment] 2024-02-02 00:43
Duplicate of #1625

**Closed by mine-cetinkaya-rundel** 2024-02-02 00:43 UTC
