### ISSUE TITLE
Typo error in Figure 12.3

### ISSUE THREAD

**Issue by zacharyleung** [hadley/r4ds#643] opened 2018-02-09 05:54 UTC
I spotted a typo error in [Figure 12.3](http://r4ds.had.co.nz/images/tidy-8.png).

The column names for the table on the left should be (country, year, **type**, **count**) rather than (country, year, **key**, **value**).

**Comment by hadley** [comment] 2020-10-04 20:33
Duplicate of #544

**Closed by hadley** 2020-10-04 20:33 UTC
